.TL
Pre calculus Readiness Test
.AU
Alexander Daumas and Elias Zarate
.AI
San Diego City College: MESA Center
.PP
This test is designed by MESA tutors to evaluate your subject readiness in Pre-Calculus. The questions showcased in the following test are not meant to be particularly challenging.
.IP "1." 4
Solve the given equation.
.EQ
x sup {2} + 7 x = 21
.EN
.IP "2." 4
Here is some more text on a list, now showing 2.
#test comment
